version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      target-branch: 'development'
      commit-message:
        prefix: 'chore(deps)'

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
